services:
  db:
    container_name: psql-kahoot
    image: postgres
    restart: unless-stopped
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - '5001:5432'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=secret

  # connection string for Postgres (with template values):
  # postgresql://postgres@localhost:5001/rmf-db1
